### PR TITLE
Config Services and NTP fixes

### PR DESCRIPTION
**Pull request by kiwichris**
I have `ntpd` working on a MVME2700 and the legacy stack.

### CODE REVIEW

**Comment by KinseyMoore** [comment]
Building under lwip encounters a missing symbol for errno_to_str since that is defined in namespace.h to prepend \_ntp\_ to the symbol which blocks that function from being included in msyslog.c. The simple fix is to remove that line from namespace.h, but I wonder where your build got that symbol and whether it would conflict.

**Comment by kiwichris** [comment]
> Building under lwip encounters a missing symbol for errno_to_str since that is defined in namespace.h to prepend _ntp_ to the symbol which blocks that function from being included in msyslog.c. The simple fix is to remove that line from namespace.h, but I wonder where your build got that symbol and whether it would conflict.

I have it sorted in my sandbox. I kept the symbol and fixed the define.

**Comment by KinseyMoore** [comment]
Did you get the update pushed that fixes the build on lwip?

**Comment by kiwichris** [comment]
The patch I put in this patch set is to handle a warning as the define in `namespace.h` triggered a lack of a prototype on RTEMS.

**Comment by kiwichris** [comment]
Updated the PR with the build fixed for no `DEBUG`

**Pull request merged**
